# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Posture.destroy_all
User.destroy_all
Diary.destroy_all

Diary.create(entry: "I feel better when finishing with plow")
Diary.create(entry: "I should spend longer in down dog after I run")

User.create(username: 'ryan', password: 'ryan')


Posture.create(name: "Child's Pose", description:'From a kneeling position, the toes and knees are together with most of the weight of the body resting on the heels of the feet. The arms extend to the front with the fingers spread wide. The forehead rest softly onto the earth. The gaze is down and inward.', level: '1', is_breathing_in: true,  image:'https://pocketyoga.com/assets/images/poses/child.png')
Posture.create(name: 'Easy Pose', description:'From a seated position, bring your knees into a simple cross legged pose. Both knees should be below the hips. Place the hands on the thighs or knees and keep the spine straight.', level: '1', is_breathing_in: true,  image:'https://pocketyoga.com/assets/images/poses/easy.png')
Posture.create(name: 'Hero', description:"From a kneeling position on the floor (with a folded blanket to pad your knees, shins, and feet if necessary) the weight of the body is centered between your feet in a seated position. If the buttocks don't comfortably rest on the floor, raise them on a block placed between the feet. Make sure both sitting bones are evenly supported. There is a thumb's-width space between the inner heels and the outer hips. The thighs are rotated inward and the heads of the thigh-bones are pressed into the earth with the bases of your palms. The hands rest on the lap, thighs or soles of the feet. The shoulder blades are firmed against the back ribs and the top of your sternum is lifted like a proud warrior. The collarbones are widened as the shoulder blades release away from the ears. The tailbone lengthens into the floor to anchor the back torso", level: '1', is_breathing_in: false,  image:'https://pocketyoga.com/assets/images/poses/hero.png')
Posture.create(name: 'Boat', description:'From a seated position the feet are lifted up so that the thighs are angled about 45-50 degrees relative to the earth. The legs are straight. The tailbone is lengthened into the earth and the pubis pulls toward the navel. The shoulder blades are spread across the back and the hands reach straight forward making the arms are parallel to the earth. The chin is tipped slightly toward the sternum so that the base of the skull lifts lightly away from the back of the neck. Gaze is forward.', level:'4', is_breathing_in: false,  image:'https://pocketyoga.com/assets/images/poses/boat_full.png')
Posture.create(name: 'Cow Face', description:'From a squatting position the feet are as close together as possible (keep your heels on the floor if you can; otherwise, support them on a folded mat). The thighs are slightly wider than the torso. The torso is leaning gently forward and tucked snugly between the thighs. The elbows are pressed against the inner knees and the palms are together in Anjali Mudra (Salutation Seal). The knees resist the elbows to help lengthen the front torso. The gaze is soft and forward.', level:'4', is_breathing_in: true,  image:'https://pocketyoga.com/assets/images/poses/knee_pile_bind_L.png')
Posture.create(name: 'Lotus', description:'bring the bottom ankle and place it on top of the opposite knee, both ankles will be resting on top of the thighs.', level: '1', is_breathing_in: true,  image:'https://pocketyoga.com/assets/images/poses/lotus_full.png')
Posture.create(name: 'Pigeon', description:'From a lounging position, the hips are parallel and squared to the earth with the front knee bent in a 90-degree angle and flat on the earth. The front foot rests close to the groin. The back leg is extended with the knee and the back foot squared, parallel and pressed firmly into the earth. The ribcage is lifted. The heart is open. Fingers rest on the earth by the side body. The gaze is forward.', level:'4', is_breathing_in: false,  image:'https://pocketyoga.com/assets/images/poses/pigeon_half_L.png')
Posture.create(name: 'Table', description:'From a kneeling position, the knees and arms form a box with the spine and neck in a neutral position. The hips and shoulders are squared to the earth and the palms are rooted with the weight of the body equally distributed between the heel of the hands and the top of the knees. The joints are stacked with the wrists, elbows and shoulders in a straight line. The gaze is down.', level:'1', is_breathing_in: false,  image:'https://pocketyoga.com/assets/images/poses/box_neutral.png')
Posture.create(name: 'Cat', description:'From Table, shift some weight to the palms. The wrists, elbows and shoulders are in one line. The abdomen is pulled in and up with the spine arched in a strong Cobra spine. The crown of the head is toward the earth and the neck is relaxed. The gaze is between the arms toward the belly.', level:'1', is_breathing_in: false,  image:'https://pocketyoga.com/assets/images/poses/cat.png')
Posture.create(name: 'Cow', description:'From table (Cakravākāsana), the ribcage is lifted with a gentle sway in the low back. The tailbone lifts up into dog tilt. The eyes are soft and the gaze is to the sky.', level: '1', is_breathing_in: true,  image:'https://pocketyoga.com/assets/images/poses/dog.png')
Posture.create(name: 'Mountain', description:'The body is in the standing position, with the feet together and rooted into the earth. The weight of the body is evenly distributed on the four corners of the feet. The pelvis is tucked. The ribcage is lifted. The neck is a natural extension of the spine and the chin is slightly tucked toward the sternum. The shoulders are relaxed as they rotate back and down. The arms at your sides. The gaze is forward.', level:'2', is_breathing_in: true,  image: 'https://pocketyoga.com/assets/images/poses/mountain_arms_side.png')
Posture.create(name: 'Forward Fold', description:"From a Standing Forward Bend (Uttānāsana), separate your feet hip-width apart and catch opposite elbows. Take a generous bend in your knees if you'd like, to allow your chest and thighs to connect. Shift some weight forward into the balls of your feet to send your sit bones up. Allow your neck and face to relax. Sway side to side to release any tension.", level:'2', is_breathing_in: false,  image: 'https://pocketyoga.com/assets/images/poses/forward_bend.png')
Posture.create(name: 'Halfway Lift', description:'From a standing position, the upper body is lifted up halfway with the feet rooted into the earth and the toes actively lifted. The spine is straight. The ribcage is lifted and connected to the thighs. The neck is a natural extension of the spine. The fingertips are next to the toes. The gaze is down and slightly forward.', level:'2', is_breathing_in: true,  image: 'https://pocketyoga.com/assets/images/poses/forward_bend_half_way.png')
Posture.create(name: 'Warrior 1', description:'From a standing position, the legs are in a wide stance with the feet aligned and flat on the earth. The back foot is in a 60-degree angle toward the front. The hips are squared. The inner thighs are rotated toward each other. The front knee is bent in a 90-degree angle directly above the ankle. The arms extend up to the sky with the biceps by the ears. The hands can be together or separated and facing each other with the fingers spread wide. The ribcage is lifted and the pelvis tucked. The gaze is forward.', level:'3', is_breathing_in: true,  image: 'https://pocketyoga.com/assets/images/poses/warrior_II_L.png')
Posture.create(name: 'Warrior 2', description:'From a standing position, the legs are separated into a wide stance. The front knee is bent in a 90-degree angle directly above the ankle. The back leg is extended and straight with the outside edge of the back foot gripping the earth in a 60-degree angle toward the front. The inner thighs are externally rotated away from each other. The pelvis is tucked. The ribcage is lifted. The arms are extended out to the sides and are aligned with the shoulders in a straight line with the fingers reaching out as the shoulder blades squeeze together. The gaze is toward the front fingers.', level:'3', is_breathing_in: true,  image: 'https://pocketyoga.com/assets/images/poses/warrior_II_L.png')
Posture.create(name: 'Warrior 3', description:'From a standing position, one leg is rooted and perpendicular to the earth while the other leg is raised, extended back and parallel to the earth. The head of the thighbone of the standing leg presses back toward the heel and is actively rooted into the earth. The arms and the extended leg lengthen in opposing directions with Bandhas engaged. The hips are squared and the tailbone presses firmly into the pelvis. The arms, torso, and extended raised leg should be positioned relatively parallel to the floor. The gaze is forward or down.', level: '3', is_breathing_in: true,  image: 'https://pocketyoga.com/assets/images/poses/warrior_III_L.png')
Posture.create(name: 'Yogi Squat', description: 'From a squatting position the feet are as close together as possible (keep your heels on the floor if you can; otherwise, support them on a folded mat). The thighs are slightly wider than the torso. The torso is leaning gently forward and tucked snugly between the thighs. The elbows are pressed against the inner knees and the palms are together in Anjali Mudra (Salutation Seal). The knees resist the elbows to help lengthen the front torso. The gaze is soft and forward.', level: '4', is_breathing_in: false,  image: 'https://pocketyoga.com/assets/images/poses/garland.png')
Posture.create(name: 'Horse Pose', description:'Step your feet to the side to the length of your mat and wide apart. Turn your toes out toward the corners, heels in. Bend your knees directly over your toes and lower your hips into a squat at the same time. Tuck your tailbone in slightly and press your hips forward as you draw your thighs back. Pull your lower belly in and lift through your rib cage. Keep your knees in line with your toes. Soften your shoulders.', level: '3', is_breathing_in: false,  image: 'https://pocketyoga.com/assets/images/poses/goddess_L.png')
Posture.create(name: 'Star Pose', description:'Begin standing in Mountain (Tāḍāsana). Step your feet apart wider than your hips, toes turned out slightly. Press into all four points of your feet and engage your legs. Tuck your tailbone slightly by bringing your pelvis to neutral. Reach your arms out to the side and energize your arms. Engage the back of your shoulders and broaden your collarbone.', level: '3', is_breathing_in: true,  image: 'https://pocketyoga.com/assets/images/poses/star_L.png')
Posture.create(name: 'Extended Side Angle', description:'The lower body stays static while the upper body folds forward at the crease of the hip. One arm is extended toward the sky while the other reaches down to the earth. The fingers reach out as the shoulder blades squeeze together. The gaze is toward the sky.', level: '3', is_breathing_in: false,  image: 'https://pocketyoga.com/assets/images/poses/warrior_II_forward_L.png')
Posture.create(name: 'Tree Pose', description:'From a standing position, one foot is rooted into the earth with the opposite heel rooted into the inner thigh with the toes pointing toward the earth. The pelvis and the chin are tucked in. The hands come together at the heart in prayer position. The gaze is forward.', level: '2', is_breathing_in: true,  image: 'https://pocketyoga.com/assets/images/poses/tree_prayer_R.png')
Posture.create(name: 'Standing Splits', description:'From standing forward bend, lift your gaze and find a focal point on the ground in front of you. Walk your fingers out slightly in front of you. Shift your weight to one foot and lift your opposite leg up toward the sky. Focus on keeping your chest connected to the thigh of your grounded leg, even if you need to take a slight bend in your knee. The hip of your lifted leg should be squared, just like your grounded leg. Keep the hip bone of your lifted leg pointed downward and your toes rotated inward toward the midline of your body.', level: '3', is_breathing_in: false,  image: 'https://pocketyoga.com/assets/images/poses/splits_standing_L.png')
Posture.create(name: 'Corpse', description:'The body rests on the earth in a supine position with the arms resting by the side body. The palms are relaxed and open toward the sky. The shoulder blades are pulled back, down and rolled under comfortably, resting evenly on the earth. The legs are extended down and splayed open. The heels are in and the toes flop out. The eyes are closed. Everything is relaxed. The gaze is inward.', level: '4', is_breathing_in: false,  image: 'https://pocketyoga.com/assets/images/poses/corpse.png')
Posture.create(name: 'Downward Facing Dog', description:'The body is positioned in an inverted "V" with the palms and feet rooted into the earth and sits bones lifted up toward the sky. The arms and legs are straight. The weight of the body is equally distributed between the hands and the feet. The eye of the elbows face forward. The ribcage is lifted and the heart is open. Shoulders are squared to the earth and rotated back, down and inward. The neck is relaxed and the crown of the head is toward the earth. The gaze is down and slightly forward.', level: '2', is_breathing_in: false,  image: 'https://pocketyoga.com/assets/images/poses/lunge_crescent_L.png')
Posture.create(name: 'Crescent Lunge', description:'The front foot of one leg is rooted on the earth with the knee directly above and tracking the ankle in a 90-degree angle. The back leg is straight, no bend in the knee, and the weight is distributed backwards onto the toes as the back heel pushes back and down toward the earth. The inner thighs scissor toward each other and the pelvis is tucked under with the ribcage lifted and the chin slightly tucked. The spine is long and extended. The heart is open. The arms are straight with no bend in the elbows or the wrists. The hands can be together or separated and facing each other with the fingers spread wide. Gaze is natural and forward.', level: '2', is_breathing_in: true,  image: 'https://pocketyoga.com/assets/images/poses/lunge_crescent_L.png')
Posture.create(name: 'Plow', description:'From a supine position, the upper back rests on the earth with the hips and legs revolved back over the torso above and beyond the head toward the earth. The torso is perpendicular to the earth. The legs are fully extended with no bend at the knees as the toes reach for the earth. The hands are either supporting the lower back or extended behind the back on the earth with extended elbows and fingers interlaced (as flexibility allows), opening the shoulders. The neck is straight. The chin tucked. Do not look to the side as this may injure the neck. The is gaze inward.', level: '4', is_breathing_in: false,  image: 'https://pocketyoga.com/assets/images/poses/plow.png')
Posture.create(name: 'Happy Baby', description:'From a supine position, on your back, the knees are bent slightly wider than the hips. The ankles and shins track the knees in a 90-degree angle perpendicular to the earth. The hands grip the inside sole of the flexed feet (if you have difficultly holding the feet loop a strap over each sole) and push the knees down, coaxing the thighs in toward the torso, lengthening the spine, releasing the tail bone toward the earth and extending the base of the skull away from the back of the neck. The gaze is up toward the sky.', level: '4', is_breathing_in: true,  image:'https://pocketyoga.com/assets/images/poses/blissful_baby.png')
Posture.create(name: 'Chair', description:'From a standing position, the feet are together and rooted into the earth with toes actively lifted. The knees are bent and the weight of the body is on the heels of the feet. The pelvis is tucked in and the ribcage is lifted. The neck is a natural extension of the spine. The arms are lifted up toward the sky with the elbows straight and the biceps by the ears. The hands can be together or separated and facing each other with the fingers spread wide. The gaze is forward.', level: '3', is_breathing_in: true,  image:'https://pocketyoga.com/assets/images/poses/chair.png')
Posture.create(name: 'Eagle', description:'From a standing position the one thigh is crossed over the other with the toes and/or the ankle hooked behind the lower calf. The weight of the body is balanced on the standing foot. The arms are crossed in front of the torso so that one arm is crossed above the other arm. The top arm is tucked into the elbow crook of the bottom arm. The hands are hooked around each other as well. Once hooked, the elbows lift up and the fingers stretch toward the sky. The gaze is soft and forward.', level: '2', is_breathing_in: false,  image:'https://pocketyoga.com/assets/images/poses/eagle_R.png')
Posture.create(name: 'Figure 4', description:'Begin in Mountain with Prayer Hands (Tāḍāsana) and lift one leg to a table top position while keeping your opposite foot rooted on the earth. Outer rotate the knee of your floating leg and place your ankle on top of the opposite thigh, above your knee. You can use your hands to slide your shin closer up. Begin to shift your weight back as if you are sitting in a chair and send some weight to the heel of your grounding foot. Flex the foot of your crossed ankle and keep outer rotating your knee as you hinge your hips back deeper. Keep your chest lifted. Hands can come to your heart and find a focal point to gaze at.', level: '2', is_breathing_in: false,  image:'https://pocketyoga.com/assets/images/poses/figure_four_L.png')
Posture.create(name: 'Half Moon', description:'From a standing position one leg is straight while the other is extended back parallel to the earth (or a little above parallel) and one hand is on the earth (beyond the little-toe side of the foot, about 12 inches) while the other hand is extended up toward the sky. The shoulder blades are squeezed together and the fingers move outward in opposing directions. The weight of the body is supported mostly by the standing leg while the bottom hand has very little weight on it but is used intelligently to regulate balance. The upper torso is rotated open to the sky. Both hips are externally rotated. Energy is extended actively through the flexed toes to keep the raised leg strong. The inner ankle of the standing foot is lifted strongly upward, as if drawing energy from the earth. The sacrum and scapulae are firmly pressed against the back torso and lengthen the coccyx toward the raised foot. The gaze is either up or down, depending on the condition of the neck. If injured the gaze is down.', level: '3', is_breathing_in: true,  image: 'https://pocketyoga.com/assets/images/poses/half_moon_L.png')
Posture.create(name: 'Humble Warrior', description:'Keep the connection with your interlaced hands, palms touching and begin to bow forward toward the inside of your front thigh. Keep a 90 degree bend in your front knee and a strong back leg by rooting down into the straight edge of your foot. Lift your interlaced hands off your lower back, up and over your head. Relax your neck and your face muscles. Try to keep your shoulders and hips squared toward the front.', level: '3', is_breathing_in: false,  image: 'https://pocketyoga.com/assets/images/poses/warrior_humble_L.png')
Posture.create(name: 'Triangle', description:'From a standing position, the legs are straight and separated into a wide stance. The feet are aligned and flat on the earth with the back foot in a 60-degree angle toward the front. The inner thighs are rotated externally away from each other. The pelvis is tucked and the ribcage is lifted. One arm extends up toward the sky as the other reaches down to the earth. Both arms are aligned with the shoulders in a straight line. The fingers reach out as the shoulder blades squeeze together. The gaze is toward the front.', level: '3', is_breathing_in: false,  image:"https://pocketyoga.com/assets/images/poses/triangle_forward_L.png")
Posture.create(name: 'Wide Legged Forward Fold', description:'Step your feet apart wider than your hips, toes turned in, heels out slightly. Press into all four points of your feet and engage your legs. Tuck your tailbone slightly by bringing your pelvis to neutral. Place your hands to your hips and hinge forward to fold. Once you can no longer go further, drop your hands underneath your head and begin to walk your hands through your legs. Drop the crown of your head down and relax your neck. Continue to draw energy up your feet and tilt your hips up and forward slightly. Keep your weight forward so your hips and ankles stay in line.', level: '3', is_breathing_in: false,  image: "https://pocketyoga.com/assets/images/poses/wide_legged_forward_bend_I_L.png")
Posture.create(name: 'Bridge', description:'From a supine position, on your back, the hips are pressed up with the heels of the feet rooted into the earth close to the sits bones. The toes are actively lifted and the pelvis tucked. The thighs are parallel to the earth and the fingers are interlaced under the body with the ribcage lifted and the heart open. The back of the neck rests on the earth. The gaze is to the sky.', level: '4', is_breathing_in: true,  image: 'https://pocketyoga.com/assets/images/poses/bridge.png')
Posture.create(name: 'Supine Spinal Twist', description:'From a supine position, bend one knee and cross it outside of the opposite foot. Use your hand to put slight pressure on the bent knee to push down toward the floor. Keep both shoulders squared and rooted to the earth. Extend the opposite hand and gaze toward the hand. For a deeper stretch, start to straighten the bent leg.', level: '4', is_breathing_in: false,  image: 'https://pocketyoga.com/assets/images/poses/supine_spinal_twist_L.png')
Posture.create(name: 'Bow', description:'From a prone position with the abdomen on the earth, the hands grip the ankles (but not the tops of the feet) with knees no wider than the width of your hips. The heels are lifted away from the buttocks and at the same time the thighs are lifted away from the earth working opposing forces as the heart center, hips and back open. The gaze is forward.', level: '4', is_breathing_in: false,  image: "https://pocketyoga.com/assets/images/poses/bow.png")

Posture.create(name: 'Cobra', description:'Begin by lying face down with your legs extended behind you, hip-width apart and the tops of your feet rested. Spread your fingers wide and place your hands under your shoulders with your fingers pointing toward the top of the mat. Hug your elbows into the sides of your body. Press down through the tops of your feet and lift your head and chest off the floor. Keep your lower ribs on the floor. Draw your shoulders back and your heart forward keeping your head a natural extension of your spine and your shoulders rolled down and away from your ears. Begin to straighten your arms and lift your chest off the floor. Press the tops of your thighs down firmly into the floor', level: '1', is_breathing_in: true,  image: "https://pocketyoga.com/assets/images/poses/cobra_full.png")